###############################################################################
#
# Makefile for a script (e.g. Python) Assembler project
#
# Translate an .asm file to an hack file
#
# Students:
# Benjamin Maman, 341145811
# Rubens  Valensi, 342414141
###############################################################################

all:
	chmod o+x Assembler
