###############################################################################
#
# Makefile for a script (e.g. Python) VMTranslator project
#
# Translate an .VM file to an ASM file
#
# Students:
# Benjamin Maman, 341145811
# Rubens  Valensi, 342414141
###############################################################################

all:
	chmod o+x VMtranslator
